[package]
name = "tracing-logger-config"
version = "0.1.2"
description = "Custom logger config for tracing"
authors = ["Rust Latam <rust.lang.latam@gmail.com>"]
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
]
repository = "https://gitlab.com/proximax-latam/celebrities"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
opentelemetry = "0.29.1"
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.29.0", features = ["rt-tokio"] }
serde = { version = "1.0", features = ["derive"] }
tracing = { version = "0.1", features = ["log"] }
tracing-appender = "0.2"
tracing-opentelemetry = "0.30.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono"] }